# The Python Programming Language

## Table of Contents
1. [Introduction](#1)
2. [Data Types](#2)
3. [Variables](#3)
4. [Functions](#4)
5. [Sequences - Tuples & Lists](#5)
6. [Sequences - Strings](#6)
7. [Date and Time](#7)
8. [Objects and Classes](#8)
9. [Lambdas and List Comprehensions](#9)
10. [Numerical Python - NumPy](#10)

<a id="1"></a>
## 1 - Introduction
Python is an interpreted, high-level, general-purpose programming language. 

Python's design philosophy emphasizes code readability, with its notable use of significant whitespace rather than curly braces control loops. 

The Python language's constructs and object-oriented approach aim to help programmers write clear, logical code for small and large-scale projects.

Python is particularly popular within the Data Science and Machine Learning community for these reasons, as well as the powerful and easy to use modules that have been made for its use.

If you would like to learn more about the Python language and how to get started using Python, I recommend the following sources:

- https://www.python.org/

- https://docs.python.org/3/tutorial/index.html

- https://www.anaconda.com/distribution/

- https://www.hackerrank.com/domains/python

<a id="2"></a>
## 2 - Data Types

Use `type` to return an object's type. Below are some examples of the base data types in Python.

In [522]:
type(1)

int

In [368]:
type(1.0)

float

In [369]:
type('This is a string')

str

In [370]:
type(None)

NoneType

In [371]:
type(True)
type(False)

bool

Programmers can define their own unique types in Python, which we will learn more about in later sections.

<a id="3"></a>
## 3 - Variables
Python does not enforce any typing on variable declarations. 

Therefore, you can create any variable by simply using the assignment `=` operand.

In [376]:
a = 12
a = 'Hello world!'
a = True
a

True

<a id="4"></a>
## 4 - Functions

In Python, functions take `input` parameters and then `return` an output.

The output type does not have to be specified.

`add_numbers` is a function that takes two numbers `x` and `y` as input.

The function adds them together, and then returns the output `result`.

In [380]:
def add_numbers(x, y):
    result = x + y
    return result

add_numbers(1, 2)

3

`add_numbers` has been updated below to take an optional 3rd parameter. 

Using `print` allows printing of multiple expressions within a single cell.

In [381]:
def add_numbers(x,y,z=None):
    if z is None:
        return x+y
    else:
        return x+y+z

print(add_numbers(1, 2))
print(add_numbers(1, 2, 3))

3
6


`add_numbers` has been updated to take an optional flag parameter.

Notice each additional update has overridden our previous function declaration.

In [385]:
def add_numbers(x, y, z=None, flag=False):
    if flag:
        print('Flag is true!')
    if z is None:
        return x + y
    else:
        return x + y + z
    
print(add_numbers(1, 2, flag=True))
print(add_numbers(1, 2, z=3))

Flag is true!
3
6


Functions can be assigned to variables in Python. 

Below, we assign function `add_numbers` to variable `a`.

In [386]:
def add_numbers(x,y):
    return x+y

a = add_numbers
a(1,2)

3

<a id="5"></a>
## 5 - Sequences (Tuples and Lists)

A tuple is an immutable data structure (cannot be altered) consisting of a sequence of objects.

In Python, sequences may contain mixed data types.

In [388]:
x = (1, 'a', 2, 'b')
type(x)

tuple

<br>
Lists are a mutable data structure, which also consist of a sequence of objects.

In [389]:
x = [1, 'a', 2, 'b']
type(x)

list

Use the `append` method to add an object to the end of a list.

In [390]:
x.append(3.3)
print(x)

[1, 'a', 2, 'b', 3.3]


Individual elements of a list or tuple can be accessed by using index notation. The first index location is 0.

In [391]:
print(x[0]) # first index
print(x[1]) # second index

1
a


This is an example of how to loop through each item in the list.

In [392]:
for item in x:
    print(item)

1
a
2
b
3.3


<br>
You can also use a while loop and index notation to loop through the list.

In [393]:
i = 0
while i != len(x):
    print(x[i])
    i = i + 1

1
a
2
b
3.3


Use `+` to concatenate lists.

In [394]:
[1,2] + [3,4]

[1, 2, 3, 4]

Use `*` to repeat lists.

In [395]:
[1]*3

[1, 1, 1]

Many operations are not supported however.

In [396]:
x - [3]

TypeError: unsupported operand type(s) for -: 'list' and 'list'

Use the `in` operator to check if something is inside a list.

In [397]:
1 in [1, 2, 3]

True

Notice that we do not need to specify data types for a list.

That means we can even create a list of lists. 

In [443]:
y = [[1,2,3],[4,5,6]]
y

[[1, 2, 3], [4, 5, 6]]

In [444]:
print(y[0][1])

2


<a id="6"></a>
## 6 - Sequences (Strings)

Strings are sequences of characters.

A string can be created by wrapping typed characters in `'`, `"`, or `"""`.

In [398]:
x = 'This is a string'
x

'This is a string'

In Python, index notation can be used for referring to individual characters in a string. 

In [399]:
print(x[0]) # first character
print(x[1]) # second character

T
h


Bracket notation can also be used for string slicing, which is often done using explicit functions in other programming languages.

In [400]:
print(x[0:1]) # first character, but we have explicitly set the end character
print(x[0:2]) # first two characters

T
Th


In Python, you can use negative indexes to access characters from the end of a string. Accessing index -1 will return the last element of the string.

In [401]:
x[-1]

'g'

<br>
This will return the slice starting from the 4th element from the end and stopping before the 2nd element from the end.

In [402]:
x[-4:-2]

'ri'

<br>
This is a slice from the beginning of the string and stopping before the 3rd element.

In [403]:
x[:3]

'Thi'

<br>
And this is a slice starting from the 4th element of the string and going all the way to the end.

In [404]:
x[3:]

's is a string'

You may simply reverse a string by writing a reverse index.

In [405]:
x[::-1]

'gnirts a si sihT'

The third parameter is how many steps through the string you would like to make.

In [406]:
x[0:8:2]

'Ti s'

There are three main ways of formatting strings in Python.

In [407]:
firstname = 'Christopher'
lastname = 'Brooks'

# Three types of formatting
print(firstname + ' ' + lastname)
print('{} {}'.format(firstname, lastname))
print(f'{firstname} {lastname}')

print(firstname*3)
print('Chris' in firstname)


Christopher Brooks
Christopher Brooks
Christopher Brooks
ChristopherChristopherChristopher
True


`split` returns a list of all the words in a string, or a list split on a specific character.

In [408]:
firstname = 'Christopher Arthur Hansen Brooks'.split(' ')[0] # [0] selects the first element of the list
lastname = 'Christopher Arthur Hansen Brooks'.split(' ')[-1] # [-1] selects the last element of the list
print(firstname)
print(lastname)

Christopher
Brooks


<br>
Make sure you convert objects to strings before concatenating.

In [409]:
'Chris' + 2

TypeError: can only concatenate str (not "int") to str

In [410]:
'Chris ' + str(2)

'Chris 2'

<br>
Dictionaries associate keys with values.

In [411]:
x = {'Daniel Alarcon': 'dfa238@nyu.edu', 'Bill Gates': 'billg@microsoft.com'}
x['Daniel Alarcon'] # Retrieve a value by using the indexing operator


'dfa238@nyu.edu'

In [412]:
x['Dylan Attal'] = None
x['Dylan Attal']

<br>
Iterate over all of the keys:

In [413]:
for name in x:
    print(x[name])

dfa238@nyu.edu
billg@microsoft.com
None


<br>
Iterate over all of the values:

In [414]:
for email in x.values():
    print(email)

dfa238@nyu.edu
billg@microsoft.com
None


<br>
Iterate over all of the items in the list:

In [415]:
for name, email in x.items():
    print(name)
    print(email)

Daniel Alarcon
dfa238@nyu.edu
Bill Gates
billg@microsoft.com
Dylan Attal
None


<br>
You can unpack a sequence into different variables:

In [416]:
x = ('Daniel', 'Alarcon', 'dfa238@nyu.edu')
fname, lname, email = x

In [417]:
fname

'Daniel'

In [418]:
lname

'Alarcon'

<br>
Make sure the number of values you are unpacking matches the number of variables being assigned.

In [419]:
x = ('Daniel', 'Alarcon', 'dfa238@nyu.edu','Bank OZK')
fname, lname, email = x

ValueError: too many values to unpack (expected 3)

<a id="7"></a>
## 7 - Dates and Times

In [420]:
import datetime as dt
import time as tm

<br>
`time` returns the current time in seconds since the Epoch. (January 1st, 1970)

In [421]:
tm.time()

1571200408.3374588

<br>
Convert the timestamp to datetime.

In [422]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2019, 10, 16, 0, 33, 33, 345206)

<br>
Handy datetime attributes:

In [423]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second 
# get year, month, day, etc.from a datetime

(2019, 10, 16, 0, 33, 33)

<br>
`timedelta` is a duration expressing the difference between two dates.

In [161]:
delta = dt.timedelta(days = 100) # create a timedelta of 100 days
delta

datetime.timedelta(days=100)

<br>
`date.today` returns the current local date.

In [424]:
today = dt.datetime.today()

In [425]:
today - delta # the date 100 days ago

datetime.datetime(2019, 7, 8, 0, 33, 44, 337277)

In [426]:
today > today-delta # compare dates

True

In [427]:
# You can pretty-print the string using strftime
today.strftime('%Y-%m-%d %H:%M:%S')

'2019-10-16 00:33:44'

In [428]:
today.strftime('%m/%d/%Y')

'10/16/2019'

strptime is used to convert strings into datetime objects.

In [429]:
dt.datetime.strptime('10/15/2019', '%m/%d/%Y')

datetime.datetime(2019, 10, 15, 0, 0)

Reference Python's datetime docs for all possible strftime and strptime formats: 
- https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior

<a id="8"></a>
## 8 - Objects and Classes

<br>
An example of a class in python:

In [430]:
class Person(object):
    def __init__(self, name, job, location,start_date='11/12/2018'):
        self.name = name
        self.job = job
        self.location = location
        self.start_date = dt.datetime.strptime(start_date,'%m/%d/%Y')
        
    def daysAtWork(self):
        today = dt.datetime.today()
        months = today - self.start_date
        return months
    
    def about(self): # method
        return f'{self.name} lives in {self.location} and works at {self.job}.'
    
    def __repr__(self):
        return f'< Person {self.name} >'

In [431]:
person = Person(name='Daniel Alarcon',
                job='Bank OZK',
                location='St. Petersburg, FL, USA')
                
print(person.name)
print(person.job)
print(person.location)
print(person.start_date)
print(person)

Daniel Alarcon
Bank OZK
St. Petersburg, FL, USA
2018-11-12 00:00:00
< Person Daniel Alarcon >


In [432]:
person.daysAtWork()

datetime.timedelta(days=338, seconds=2032, microseconds=923779)

<a id="9"></a>
## 9 - Lambda and List Comprehensions

<br>
Here's an example of lambda that takes in three parameters and adds the first two.

In [435]:
my_function = lambda a, b, c : a + b

In [436]:
my_function(1, 2, 3)

3

<br>
Let's iterate from 0 to 999 and return the even numbers.

In [437]:
my_list = []
for number in range(0, 1000):
    if number % 2 == 0:
        my_list.append(number)
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

<br>
Now the same thing but with list comprehension.

In [438]:
my_list = [number for number in range(0,1000) if number % 2 == 0]
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

<a id="10"></a>
## 10 - Numerical Python (NumPy)

In [439]:
import numpy as np

### 10 - A Creating Arrays

Create a list and convert it to a numpy array

In [445]:
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

<br>
Or just pass in a list directly

In [472]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

<br>
Pass in a list of lists to create a multidimensional array.

In [447]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

<br>
Use the shape method to find the dimensions of the array. (rows, columns)

In [448]:
m.shape

(2, 3)

`arange` returns evenly spaced values within a given interval.

In [449]:
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

`reshape` returns an array with the same data with a new shape.

In [450]:
n = n.reshape(3, 5) # reshape array to be 3x5
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

`linspace` returns evenly spaced numbers over a specified interval.

In [451]:
o = np.linspace(0, 4, 9) # return 9 evenly spaced values from 0 to 4
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

`resize` changes the shape and size of array in-place.

In [452]:
o.resize(3, 3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

`ones` returns a new array of given shape and type, filled with ones.

In [453]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

`zeros` returns a new array of given shape and type, filled with zeros.

In [86]:
np.zeros((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

`eye` returns a 2-D array with ones on the diagonal and zeros elsewhere.

In [454]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

<br>
`diag` extracts a diagonal or constructs a diagonal array.

In [473]:
y = np.array([4, 5, 6])
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

Create an array using repeating list.

In [459]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

Repeat elements of an array using `repeat`.

In [460]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

### 10 - B Combining Arrays

In [462]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

Use `vstack` to stack arrays in sequence vertically (row wise).

In [464]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

Use `hstack` to stack arrays in sequence horizontally (column wise).

In [466]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

### 10 - C Operations

Use `+`, `-`, `*`, `/` and `**` to perform element wise addition, subtraction, multiplication, division and power.

In [467]:
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]

[5 7 9]
[-3 -3 -3]


In [468]:
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # elementwise divison         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

[ 4 10 18]
[0.25 0.4  0.5 ]


In [469]:
print(x**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

[1 4 9]


**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [474]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

32

In [476]:
y = np.array([4, 5, 6])
z = np.array([y, y**2])
print(len(z)) # number of rows of array

2


<br>
Let's look at transposing arrays. Transposing permutes the dimensions of the array.

In [477]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

The shape of array `z` is `(2,3)` before transposing.

In [478]:
z.shape

(2, 3)

Use `.T` to get the transpose.

In [479]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

<br>
The number of rows has swapped with the number of columns.

In [480]:
z.T.shape

(3, 2)

Use `.dtype` to see the data type of the elements in the array.

In [481]:
z.dtype

dtype('int64')

Use `.astype` to cast to a specific type.

In [482]:
z = z.astype('f')
z.dtype

dtype('float32')

### 10 - D Math Functions

Numpy has many built in math functions that can be performed on arrays.

In [483]:
a = np.array([-4, -2, 1, 3, 5])

In [484]:
a.sum()

3

In [485]:
a.max()

5

In [486]:
a.min()

-4

In [487]:
a.mean()

0.6

In [490]:
a.std()

3.2619012860600183

`argmax` and `argmin` return the index of the maximum and minimum values in the array.

In [113]:
a.argmax()

4

In [114]:
a.argmin()

0

### 10 - E Indexing / Slicing

In [495]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

<br>
Use bracket notation to get the value at a specific index. Remember that indexing starts at 0.

In [496]:
s[0], s[4], s[-1]

(0, 16, 144)

Use `:` to indicate a range. `array[start:stop]`


Leaving `start` or `stop` empty will default to the beginning/end of the array.

In [117]:
s[1:5]

array([ 1,  4,  9, 16])

<br>
Use negatives to count from the back.

In [118]:
s[-4:]

array([ 81, 100, 121, 144])

A second `:` can be used to indicate step-size. `array[start:stop:stepsize]`

Here we are starting 5th element from the end, and counting backwards by 2 until the beginning of the array is reached.

In [119]:
s[-5::-2]

array([64, 36, 16,  4,  0])

In [123]:
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [127]:
s[::-1]

array([144, 121, 100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0])

<br>
Let's look at a multidimensional array.

In [501]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

Use bracket notation to slice: `array[row, column]`

In [502]:
r[2, 2]

14

In [503]:
r[2][2]

14

<br>
And use : to select a range of rows or columns

In [504]:
r[3, 3:6]

array([21, 22, 23])

In [505]:
r[3][3:6]

array([21, 22, 23])

<br>
Here we are selecting all the rows up to (and not including) row 2, and all the columns up to (and not including) the last column.

In [506]:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

<br>
This is a slice of the last row, and only every other element.

In [507]:
r[-1, ::2]

array([30, 32, 34])

We can also perform conditional indexing. Here we are selecting values from the array that are greater than 30. (Also see `np.where`)

In [508]:
r[r > 30]

array([31, 32, 33, 34, 35])

<br>
Here we are assigning all values in the array that are greater than 30 to the value of 30.

In [509]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

### 10 - F Copying Data

Be careful with copying and modifying arrays in NumPy!


`r2` is a slice of `r`

In [510]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

<br>
Set this slice's values to zero ([:] selects the entire array)

In [511]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

<br>
`r` has also been changed!

In [512]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

<br>
To avoid this, use `r.copy` to create a copy that will not affect the original array

In [513]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

<br>
Now when r_copy is modified, r will not be changed.

In [514]:
r_copy[:] = 10
print(r_copy, '\n')
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


### 10 - G Iterating Over Arrays

Let's create a new 4 by 3 array of random numbers 0-9.

In [515]:
test = np.random.randint(0, 10, (4,3))
test

array([[9, 5, 5],
       [4, 2, 2],
       [1, 7, 5],
       [7, 0, 0]])

<br>
Iterate by row:

In [516]:
for row in test:
    print(row)

[9 5 5]
[4 2 2]
[1 7 5]
[7 0 0]


<br>
Iterate by index:

In [518]:
for i in range(len(test)):
    print(test[i])

[9 5 5]
[4 2 2]
[1 7 5]
[7 0 0]


<br>
Iterate by row and index:

In [519]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [9 5 5]
row 1 is [4 2 2]
row 2 is [1 7 5]
row 3 is [7 0 0]


<br>
Use `zip` to iterate over multiple iterables.

In [520]:
test2 = test**2
test2

array([[81, 25, 25],
       [16,  4,  4],
       [ 1, 49, 25],
       [49,  0,  0]])

In [521]:
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)

[9 5 5] + [81 25 25] = [90 30 30]
[4 2 2] + [16  4  4] = [20  6  6]
[1 7 5] + [ 1 49 25] = [ 2 56 30]
[7 0 0] + [49  0  0] = [56  0  0]
